kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - ports:
    - port: {{ .Values.port }}
      protocol: TCP
  egress:
  - to:
    {{ $privateSubnets := list "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" -}}
    {{ range $index, $privateSubnet := $privateSubnets -}}
    - ipBlock:
        cidr: {{ $privateSubnet }}
    {{ end -}}
