apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.port  }}"
    prometheus.io/scheme: "http"
    giantswarm.io/monitoring-port: "{{ .Values.port  }}"
spec:
  ports:
  - port: {{ .Values.port }}
    name: {{ .Values.portName }}
  selector:
    {{- include "labels.selector" . | nindent 4 }}
